---
model: RS2
images:
    - '[![](img/reachrs2/Quickstart.png){: style="width: 200px;"} ](quickstart.md)'
    - '[![](img/reachrs2/Tutorials.png){: style="width: 200px;"}](tutorials.md)'
    - '[![](img/reachrs2/ReachView.png){: style="width: 200px;"}](common/reachview)'
    - '[![](img/reachrs2/Placement.png){: style="width: 200px;"} ](placement.md)'
    - '[![](img/reachrs2/Power-supply.png){: style="width: 200px;"}](power-supply.md)'
    - '[![](img/reachrs2/Specs.png){: style="width: 200px;"}](specs.md)'
inthebox:
    - '* 1 x Reach RS2 receiver'
    - '* 1 x Carry case'
    - '* 1 x Radio antenna'
    - '* 1 x USB-C cable'
